import type { Metadata } from "next";
import { Montserrat } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import Copyright from "@/components/Copyright";
import { Providers } from "./providers";
import { Toaster } from "@/components/ui/toaster";
import Theme from "@/components/Theme";

const mont = Montserrat({ 
  variable: '--font-mont',
  subsets: ["latin"] 
});

export const metadata: Metadata = {
  title: "shaad",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={mont.className}>
        <Providers>
          <Navbar />
            <main>
              {children}
            </main>
          <Theme />
          <Toaster />
          <Copyright />
        </Providers>
      </body>
    </html>
  );
}
