import type { Metadata } from "next";
import { Montserrat } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";

const mont = Montserrat({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "shaad",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={mont.className && 'bg-neutral-900'}>
        <Navbar />
        
        <main>{children}</main>
      </body>
    </html>
  );
}
